# Generated by Django 2.2.5 on 2019-09-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='garage',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='manager.Garage', verbose_name='add cars'),
        ),
    ]
